# Generated by Django 2.2.5 on 2021-01-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210120_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tempFile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
